export type PresetIngredient = {
  name: string
  aliases: string[]
  aisle: string
}

export const PRESET_INGREDIENTS: PresetIngredient[] = [

  // ── Produce ──────────────────────────────────────────────────────────────
  { name: 'Garlic', aliases: ['garlic clove', 'garlic cloves', 'cloves of garlic', 'fresh garlic', 'whole garlic'], aisle: 'Produce' },
  { name: 'Onion', aliases: ['onions', 'yellow onion', 'yellow onions', 'white onion', 'white onions', 'medium onion'], aisle: 'Produce' },
  { name: 'Red onion', aliases: ['red onions'], aisle: 'Produce' },
  { name: 'Shallots', aliases: ['shallot'], aisle: 'Produce' },
  { name: 'Green onions', aliases: ['scallions', 'scallion', 'green onion', 'spring onions', 'spring onion'], aisle: 'Produce' },
  { name: 'Fresh ginger', aliases: ['ginger', 'ginger root', 'knob of ginger'], aisle: 'Produce' },
  { name: 'Lemon', aliases: ['lemons', 'fresh lemon', 'Meyer lemon'], aisle: 'Produce' },
  { name: 'Lime', aliases: ['limes', 'fresh lime', 'key lime'], aisle: 'Produce' },
  { name: 'Orange', aliases: ['oranges', 'navel orange', 'fresh orange'], aisle: 'Produce' },
  { name: 'Apple', aliases: ['apples', 'Granny Smith apple', 'Honeycrisp apple', 'red apple', 'green apple'], aisle: 'Produce' },
  { name: 'Banana', aliases: ['bananas', 'ripe banana', 'ripe bananas'], aisle: 'Produce' },
  { name: 'Strawberries', aliases: ['strawberry', 'fresh strawberries', 'hulled strawberries'], aisle: 'Produce' },
  { name: 'Blueberries', aliases: ['blueberry', 'fresh blueberries'], aisle: 'Produce' },
  { name: 'Tomato', aliases: ['tomatoes', 'fresh tomato', 'roma tomato', 'roma tomatoes', 'plum tomato', 'beefsteak tomato'], aisle: 'Produce' },
  { name: 'Cherry tomatoes', aliases: ['cherry tomato', 'grape tomatoes', 'grape tomato'], aisle: 'Produce' },
  { name: 'Cucumber', aliases: ['cucumbers', 'English cucumber', 'hothouse cucumber'], aisle: 'Produce' },
  { name: 'Bell pepper', aliases: ['bell peppers', 'red bell pepper', 'green bell pepper', 'yellow bell pepper', 'orange bell pepper', 'capsicum', 'sweet pepper'], aisle: 'Produce' },
  { name: 'Jalapeño', aliases: ['jalapeños', 'jalapeno', 'jalapenos', 'jalapeño pepper', 'jalapeño peppers'], aisle: 'Produce' },
  { name: 'Avocado', aliases: ['avocados', 'ripe avocado', 'Hass avocado'], aisle: 'Produce' },
  { name: 'Spinach', aliases: ['baby spinach', 'fresh spinach', 'spinach leaves'], aisle: 'Produce' },
  { name: 'Kale', aliases: ['kale leaves', 'baby kale', 'curly kale', 'lacinato kale', 'Tuscan kale'], aisle: 'Produce' },
  { name: 'Romaine lettuce', aliases: ['romaine', 'romaine hearts', 'cos lettuce', 'lettuce'], aisle: 'Produce' },
  { name: 'Celery', aliases: ['celery stalks', 'celery stalk', 'celery ribs'], aisle: 'Produce' },
  { name: 'Carrots', aliases: ['carrot', 'whole carrots', 'large carrots'], aisle: 'Produce' },
  { name: 'Baby carrots', aliases: ['baby carrot', 'mini carrots', 'snacking carrots'], aisle: 'Produce' },
  { name: 'Shredded carrots', aliases: ['grated carrots', 'matchstick carrots', 'julienned carrots', 'carrot shreds'], aisle: 'Produce' },
  { name: 'Broccoli', aliases: ['broccoli florets', 'broccoli crowns', 'broccoli head'], aisle: 'Produce' },
  { name: 'Cauliflower', aliases: ['cauliflower florets', 'cauliflower head'], aisle: 'Produce' },
  { name: 'Zucchini', aliases: ['zucchinis', 'courgette', 'courgettes', 'zucchini squash', 'summer squash'], aisle: 'Produce' },
  { name: 'Sweet potato', aliases: ['sweet potatoes', 'yam', 'yams'], aisle: 'Produce' },
  { name: 'Potato', aliases: ['potatoes', 'russet potato', 'russet potatoes', 'Yukon Gold potato', 'Yukon Gold potatoes'], aisle: 'Produce' },
  { name: 'Mushrooms', aliases: ['mushroom', 'cremini mushrooms', 'baby bella mushrooms', 'button mushrooms', 'white mushrooms', 'crimini mushrooms'], aisle: 'Produce' },
  { name: 'Corn', aliases: ['sweet corn', 'corn on the cob', 'corn kernels', 'ears of corn'], aisle: 'Produce' },
  { name: 'Asparagus', aliases: ['asparagus spears', 'asparagus stalks'], aisle: 'Produce' },
  { name: 'Green beans', aliases: ['green bean', 'string beans', 'haricots verts', 'snap beans'], aisle: 'Produce' },
  { name: 'Cilantro', aliases: ['fresh cilantro', 'coriander leaves', 'fresh coriander', 'cilantro leaves'], aisle: 'Produce' },
  { name: 'Parsley', aliases: ['fresh parsley', 'flat-leaf parsley', 'Italian parsley', 'curly parsley'], aisle: 'Produce' },
  { name: 'Basil', aliases: ['fresh basil', 'basil leaves', 'sweet basil'], aisle: 'Produce' },
  { name: 'Mint', aliases: ['fresh mint', 'mint leaves', 'peppermint'], aisle: 'Produce' },
  { name: 'Fresh thyme', aliases: ['thyme sprigs', 'thyme sprig', 'thyme (fresh)'], aisle: 'Produce' },
  { name: 'Fresh rosemary', aliases: ['rosemary sprigs', 'rosemary sprig', 'rosemary (fresh)'], aisle: 'Produce' },

  // ── Meat & Seafood ───────────────────────────────────────────────────────
  { name: 'Chicken breast', aliases: ['chicken breasts', 'boneless skinless chicken breast', 'boneless skinless chicken breasts', 'boneless chicken breast', 'chicken breast halves'], aisle: 'Meat & Seafood' },
  { name: 'Chicken thighs', aliases: ['chicken thigh', 'boneless skinless chicken thighs', 'boneless chicken thighs', 'skin-on chicken thighs', 'bone-in chicken thighs'], aisle: 'Meat & Seafood' },
  { name: 'Chicken tenders', aliases: ['chicken tenderloins', 'chicken fingers', 'chicken strips'], aisle: 'Meat & Seafood' },
  { name: 'Whole chicken', aliases: ['roasting chicken', 'fryer chicken', 'broiler chicken'], aisle: 'Meat & Seafood' },
  { name: 'Ground beef', aliases: ['ground beef 80/20', 'ground beef 85/15', 'minced beef', 'beef mince', 'hamburger meat', 'lean ground beef'], aisle: 'Meat & Seafood' },
  { name: 'Beef steak', aliases: ['steak', 'sirloin steak', 'ribeye steak', 'flank steak', 'strip steak', 'NY strip', 'New York strip', 'skirt steak'], aisle: 'Meat & Seafood' },
  { name: 'Ground turkey', aliases: ['turkey mince', 'lean ground turkey'], aisle: 'Meat & Seafood' },
  { name: 'Pork chops', aliases: ['pork chop', 'bone-in pork chops', 'boneless pork chops'], aisle: 'Meat & Seafood' },
  { name: 'Pork tenderloin', aliases: ['pork loin', 'pork loin roast'], aisle: 'Meat & Seafood' },
  { name: 'Bacon', aliases: ['bacon strips', 'smoked bacon', 'thick-cut bacon', 'streaky bacon', 'rashers', 'unsmoked bacon'], aisle: 'Meat & Seafood' },
  { name: 'Ham', aliases: ['deli ham', 'sliced ham', 'cooked ham', 'ham steak'], aisle: 'Meat & Seafood' },
  { name: 'Italian sausage', aliases: ['sausage', 'pork sausage', 'Italian pork sausage', 'sausage links', 'ground sausage'], aisle: 'Meat & Seafood' },
  { name: 'Salmon', aliases: ['salmon fillet', 'salmon fillets', 'fresh salmon', 'Atlantic salmon', 'salmon steaks'], aisle: 'Meat & Seafood' },
  { name: 'Shrimp', aliases: ['shrimps', 'prawns', 'large shrimp', 'jumbo shrimp', 'raw shrimp', 'peeled shrimp', 'deveined shrimp'], aisle: 'Meat & Seafood' },
  { name: 'Tilapia', aliases: ['tilapia fillets', 'tilapia fillet'], aisle: 'Meat & Seafood' },
  { name: 'Cod', aliases: ['cod fillets', 'cod fillet', 'white fish'], aisle: 'Meat & Seafood' },
  { name: 'Tuna steak', aliases: ['ahi tuna', 'ahi tuna steak', 'yellowfin tuna'], aisle: 'Meat & Seafood' },

  // ── Dairy & Eggs ─────────────────────────────────────────────────────────
  { name: 'Eggs', aliases: ['egg', 'large eggs', 'large egg', 'whole eggs', 'whole egg', 'eggs (large)', 'free-range eggs', 'organic eggs'], aisle: 'Dairy & Eggs' },
  { name: 'Butter', aliases: ['unsalted butter', 'salted butter', 'stick of butter', 'butter stick', 'softened butter', 'melted butter', 'cold butter'], aisle: 'Dairy & Eggs' },
  { name: 'Milk', aliases: ['whole milk', '2% milk', '1% milk', 'skim milk', 'dairy milk'], aisle: 'Dairy & Eggs' },
  { name: 'Reduced-fat milk', aliases: ['reduced-fat milk'], aisle: 'Dairy & Eggs' },
  { name: 'Heavy cream', aliases: ['heavy whipping cream', 'whipping cream', 'double cream', 'thickened cream'], aisle: 'Dairy & Eggs' },
  { name: 'Half and half', aliases: ['half & half', 'coffee cream'], aisle: 'Dairy & Eggs' },
  { name: 'Cream cheese', aliases: ['block cream cheese', 'softened cream cheese', 'full-fat cream cheese', 'regular cream cheese'], aisle: 'Dairy & Eggs' },
  { name: 'Sour cream', aliases: ['full-fat sour cream', 'light sour cream', 'reduced-fat sour cream'], aisle: 'Dairy & Eggs' },
  { name: 'Greek yogurt', aliases: ['plain Greek yogurt', 'plain yogurt', 'yogurt', 'full-fat Greek yogurt', 'nonfat Greek yogurt', 'strained yogurt'], aisle: 'Dairy & Eggs' },
  { name: 'Cheddar cheese', aliases: ['cheddar', 'shredded cheddar', 'sharp cheddar', 'mild cheddar', 'cheddar shreds', 'grated cheddar'], aisle: 'Dairy & Eggs' },
  { name: 'Mozzarella (shredded)', aliases: ['shredded mozzarella', 'mozzarella cheese', 'low-moisture mozzarella', 'part-skim mozzarella', 'mozzarella shreds'], aisle: 'Dairy & Eggs' },
  { name: 'Fresh mozzarella', aliases: ['mozzarella balls', 'buffalo mozzarella', 'fresh mozzarella cheese', 'bocconcini'], aisle: 'Dairy & Eggs' },
  { name: 'Parmesan', aliases: ['parmesan cheese', 'Parmigiano-Reggiano', 'grated parmesan', 'shredded parmesan', 'Pecorino Romano'], aisle: 'Dairy & Eggs' },
  { name: 'Feta cheese', aliases: ['feta', 'crumbled feta', 'block feta', 'Greek feta'], aisle: 'Dairy & Eggs' },
  { name: 'Ricotta', aliases: ['ricotta cheese', 'whole milk ricotta', 'part-skim ricotta'], aisle: 'Dairy & Eggs' },
  { name: 'Cottage cheese', aliases: ['low-fat cottage cheese', 'full-fat cottage cheese', 'small-curd cottage cheese'], aisle: 'Dairy & Eggs' },
  { name: 'Buttermilk', aliases: ['low-fat buttermilk', 'cultured buttermilk'], aisle: 'Dairy & Eggs' },

  // ── Pantry & Canned ──────────────────────────────────────────────────────
  { name: 'Olive oil', aliases: ['extra virgin olive oil', 'EVOO', 'extra-virgin olive oil', 'light olive oil'], aisle: 'Pantry & Canned' },
  { name: 'Vegetable oil', aliases: ['canola oil', 'neutral oil', 'cooking oil', 'sunflower oil'], aisle: 'Pantry & Canned' },
  { name: 'Sesame oil', aliases: ['toasted sesame oil', 'dark sesame oil', 'Asian sesame oil'], aisle: 'Pantry & Canned' },
  { name: 'Coconut oil', aliases: ['refined coconut oil', 'unrefined coconut oil', 'virgin coconut oil'], aisle: 'Pantry & Canned' },
  { name: 'All-purpose flour', aliases: ['flour', 'plain flour', 'AP flour', 'all purpose flour', 'white flour'], aisle: 'Pantry & Canned' },
  { name: 'Bread flour', aliases: ['strong flour', 'strong white flour'], aisle: 'Pantry & Canned' },
  { name: 'Granulated sugar', aliases: ['sugar', 'white sugar', 'cane sugar', 'regular sugar'], aisle: 'Pantry & Canned' },
  { name: 'Brown sugar', aliases: ['light brown sugar', 'dark brown sugar', 'packed brown sugar', 'soft brown sugar'], aisle: 'Pantry & Canned' },
  { name: 'Powdered sugar', aliases: ["confectioners' sugar", 'confectioners sugar', 'icing sugar', '10x sugar'], aisle: 'Pantry & Canned' },
  { name: 'Honey', aliases: ['raw honey', 'local honey', 'clover honey', 'runny honey'], aisle: 'Pantry & Canned' },
  { name: 'Maple syrup', aliases: ['pure maple syrup', 'real maple syrup', 'dark maple syrup'], aisle: 'Pantry & Canned' },
  { name: 'Soy sauce', aliases: ['regular soy sauce', 'low-sodium soy sauce', 'tamari', 'shoyu', 'light soy sauce', 'dark soy sauce'], aisle: 'Pantry & Canned' },
  { name: 'Fish sauce', aliases: ['nam pla', 'Thai fish sauce'], aisle: 'Pantry & Canned' },
  { name: 'Worcestershire sauce', aliases: ['Worcestershire', 'worcestershire'], aisle: 'Pantry & Canned' },
  { name: 'Hot sauce', aliases: ['Tabasco', 'Louisiana hot sauce', "Frank's RedHot"], aisle: 'Pantry & Canned' },
  { name: 'Sriracha', aliases: ['sriracha sauce', 'chili garlic sauce'], aisle: 'Pantry & Canned' },
  { name: 'Ketchup', aliases: ['catsup', 'tomato ketchup'], aisle: 'Pantry & Canned' },
  { name: 'Mustard', aliases: ['Dijon mustard', 'yellow mustard', 'whole grain mustard', 'stone-ground mustard', 'spicy brown mustard'], aisle: 'Pantry & Canned' },
  { name: 'Mayonnaise', aliases: ['mayo', 'light mayo', "Duke's mayo", "Hellmann's"], aisle: 'Pantry & Canned' },
  { name: 'Apple cider vinegar', aliases: ['ACV', 'cider vinegar', 'raw apple cider vinegar'], aisle: 'Pantry & Canned' },
  { name: 'White wine vinegar', aliases: ['white vinegar', 'distilled white vinegar'], aisle: 'Pantry & Canned' },
  { name: 'Balsamic vinegar', aliases: ['balsamic', 'balsamic glaze', 'aged balsamic'], aisle: 'Pantry & Canned' },
  { name: 'Rice vinegar', aliases: ['rice wine vinegar', 'unseasoned rice vinegar', 'seasoned rice vinegar'], aisle: 'Pantry & Canned' },
  { name: 'Diced tomatoes', aliases: ['canned diced tomatoes', 'fire-roasted diced tomatoes', 'chopped tomatoes', 'canned tomatoes'], aisle: 'Pantry & Canned' },
  { name: 'Crushed tomatoes', aliases: ['canned crushed tomatoes', 'crushed plum tomatoes', 'passata'], aisle: 'Pantry & Canned' },
  { name: 'Tomato paste', aliases: ['tomato concentrate', 'double-concentrate tomato paste'], aisle: 'Pantry & Canned' },
  { name: 'Marinara sauce', aliases: ['tomato sauce', 'pasta sauce', 'spaghetti sauce'], aisle: 'Pantry & Canned' },
  { name: 'Chicken broth', aliases: ['chicken stock', 'low-sodium chicken broth', 'chicken bone broth', 'chicken broth/stock'], aisle: 'Pantry & Canned' },
  { name: 'Beef broth', aliases: ['beef stock', 'low-sodium beef broth', 'beef bone broth'], aisle: 'Pantry & Canned' },
  { name: 'Vegetable broth', aliases: ['vegetable stock', 'low-sodium vegetable broth'], aisle: 'Pantry & Canned' },
  { name: 'Black beans', aliases: ['canned black beans', 'dried black beans', 'black bean'], aisle: 'Pantry & Canned' },
  { name: 'Chickpeas', aliases: ['garbanzo beans', 'canned chickpeas', 'dried chickpeas', 'garbanzo'], aisle: 'Pantry & Canned' },
  { name: 'Kidney beans', aliases: ['canned kidney beans', 'red kidney beans', 'dark red kidney beans'], aisle: 'Pantry & Canned' },
  { name: 'Lentils', aliases: ['red lentils', 'green lentils', 'brown lentils', 'black lentils', 'French lentils'], aisle: 'Pantry & Canned' },
  { name: 'Coconut milk', aliases: ['canned coconut milk', 'full-fat coconut milk', 'lite coconut milk', 'coconut cream'], aisle: 'Pantry & Canned' },
  { name: 'White rice', aliases: ['rice', 'long-grain white rice', 'long grain rice'], aisle: 'Pantry & Canned' },
  { name: 'Brown rice', aliases: ['long-grain brown rice', 'whole grain rice'], aisle: 'Pantry & Canned' },
  { name: 'Jasmine rice', aliases: ['Thai jasmine rice', 'fragrant rice', 'jasmine white rice'], aisle: 'Pantry & Canned' },
  { name: 'Basmati rice', aliases: ['Indian basmati rice', 'long-grain basmati', 'basmati'], aisle: 'Pantry & Canned' },
  { name: 'Spaghetti', aliases: ['spaghetti noodles', 'thin spaghetti', 'angel hair pasta', 'linguine', 'linguini'], aisle: 'Pantry & Canned' },
  { name: 'Penne', aliases: ['penne pasta', 'penne rigate', 'rigatoni', 'ziti'], aisle: 'Pantry & Canned' },
  { name: 'Fettuccine', aliases: ['fettuccini', 'egg noodles', 'tagliatelle', 'pasta noodles'], aisle: 'Pantry & Canned' },
  { name: 'Rolled oats', aliases: ['oats', 'old-fashioned oats', 'oatmeal', 'quick oats', 'quick-cooking oats'], aisle: 'Pantry & Canned' },
  { name: 'Panko breadcrumbs', aliases: ['panko', 'breadcrumbs', 'Italian breadcrumbs', 'plain breadcrumbs', 'bread crumbs'], aisle: 'Pantry & Canned' },
  { name: 'Canned tuna', aliases: ['tuna in water', 'chunk light tuna', 'albacore tuna', 'tuna fish'], aisle: 'Pantry & Canned' },
  { name: 'Peanut butter', aliases: ['creamy peanut butter', 'chunky peanut butter', 'natural peanut butter', 'smooth peanut butter'], aisle: 'Pantry & Canned' },
  { name: 'Chocolate chips', aliases: ['dark chocolate chips', 'semi-sweet chocolate chips', 'milk chocolate chips', 'bittersweet chocolate chips'], aisle: 'Pantry & Canned' },

  // ── Bulk & Spices ─────────────────────────────────────────────────────────
  { name: 'Salt', aliases: ['kosher salt', 'table salt', 'sea salt', 'coarse salt', 'fine sea salt', 'iodized salt', 'flaky salt'], aisle: 'Bulk & Spices' },
  { name: 'Black pepper', aliases: ['ground black pepper', 'freshly ground pepper', 'pepper', 'cracked black pepper', 'freshly ground black pepper'], aisle: 'Bulk & Spices' },
  { name: 'Garlic powder', aliases: ['garlic granules', 'powdered garlic'], aisle: 'Bulk & Spices' },
  { name: 'Onion powder', aliases: ['onion granules', 'powdered onion'], aisle: 'Bulk & Spices' },
  { name: 'Paprika', aliases: ['smoked paprika', 'sweet paprika', 'Hungarian paprika', 'hot paprika'], aisle: 'Bulk & Spices' },
  { name: 'Cumin', aliases: ['ground cumin', 'cumin seeds', 'cumin powder', 'whole cumin'], aisle: 'Bulk & Spices' },
  { name: 'Chili powder', aliases: ['chilli powder', 'chili seasoning', 'ancho chili powder', 'chipotle chili powder'], aisle: 'Bulk & Spices' },
  { name: 'Cayenne pepper', aliases: ['cayenne', 'ground cayenne', 'cayenne powder'], aisle: 'Bulk & Spices' },
  { name: 'Red pepper flakes', aliases: ['crushed red pepper', 'crushed red pepper flakes', 'chili flakes', 'hot pepper flakes'], aisle: 'Bulk & Spices' },
  { name: 'Dried oregano', aliases: ['oregano', 'Italian oregano', 'Mediterranean oregano'], aisle: 'Bulk & Spices' },
  { name: 'Dried thyme', aliases: ['thyme', 'ground thyme', 'dried thyme leaves'], aisle: 'Bulk & Spices' },
  { name: 'Dried rosemary', aliases: ['rosemary', 'rosemary leaves', 'crushed rosemary'], aisle: 'Bulk & Spices' },
  { name: 'Dried basil', aliases: ['basil (dried)', 'dried sweet basil'], aisle: 'Bulk & Spices' },
  { name: 'Cinnamon', aliases: ['ground cinnamon', 'cinnamon powder', 'Ceylon cinnamon'], aisle: 'Bulk & Spices' },
  { name: 'Nutmeg', aliases: ['ground nutmeg', 'freshly grated nutmeg'], aisle: 'Bulk & Spices' },
  { name: 'Turmeric', aliases: ['ground turmeric', 'turmeric powder'], aisle: 'Bulk & Spices' },
  { name: 'Curry powder', aliases: ['curry spice', 'mild curry powder', 'Madras curry powder'], aisle: 'Bulk & Spices' },
  { name: 'Italian seasoning', aliases: ['Italian herbs', 'mixed Italian herbs', 'dried Italian seasoning'], aisle: 'Bulk & Spices' },
  { name: 'Bay leaves', aliases: ['bay leaf', 'dried bay leaves', 'dried bay leaf'], aisle: 'Bulk & Spices' },
  { name: 'Vanilla extract', aliases: ['pure vanilla extract', 'vanilla', 'vanilla bean paste', 'vanilla beans'], aisle: 'Bulk & Spices' },
  { name: 'Baking powder', aliases: ['double-acting baking powder'], aisle: 'Bulk & Spices' },
  { name: 'Baking soda', aliases: ['bicarbonate of soda', 'bicarbonate', 'sodium bicarbonate'], aisle: 'Bulk & Spices' },
  { name: 'Cornstarch', aliases: ['corn starch', 'cornflour', 'corn flour', 'maize starch'], aisle: 'Bulk & Spices' },
  { name: 'Cocoa powder', aliases: ['unsweetened cocoa powder', 'Dutch-process cocoa', 'natural cocoa powder'], aisle: 'Bulk & Spices' },
  { name: 'Coriander (spice)', aliases: ['ground coriander', 'coriander seeds', 'coriander powder'], aisle: 'Bulk & Spices' },
  { name: 'Garam masala', aliases: ['garam masala spice blend'], aisle: 'Bulk & Spices' },
  { name: 'Allspice', aliases: ['ground allspice', 'whole allspice'], aisle: 'Bulk & Spices' },
  { name: 'Dried dill', aliases: ['dill weed', 'dill', 'dill flakes'], aisle: 'Bulk & Spices' },
  { name: 'Almonds', aliases: ['whole almonds', 'sliced almonds', 'slivered almonds', 'almond', 'blanched almonds', 'raw almonds'], aisle: 'Bulk & Spices' },
  { name: 'Walnuts', aliases: ['walnut', 'walnut halves', 'chopped walnuts', 'English walnuts'], aisle: 'Bulk & Spices' },
  { name: 'Pine nuts', aliases: ['pine nut', 'pignoli', 'pignoli nuts'], aisle: 'Bulk & Spices' },
  { name: 'Pecans', aliases: ['pecan', 'pecan halves', 'chopped pecans'], aisle: 'Bulk & Spices' },

  // ── Bakery ────────────────────────────────────────────────────────────────
  { name: 'Sandwich bread', aliases: ['white bread', 'whole wheat bread', 'sliced bread', 'bread', 'pullman loaf'], aisle: 'Bakery' },
  { name: 'Sourdough bread', aliases: ['sourdough loaf', 'sourdough', 'sourdough boule'], aisle: 'Bakery' },
  { name: 'Baguette', aliases: ['French baguette', 'French bread', 'French loaf'], aisle: 'Bakery' },
  { name: 'Flour tortillas', aliases: ['tortillas', 'corn tortillas', 'tortilla', 'soft tortillas', 'burrito-size tortillas', 'taco-size tortillas'], aisle: 'Bakery' },
  { name: 'Pita bread', aliases: ['pita', 'flatbread', 'pitas', 'pocket pita'], aisle: 'Bakery' },
  { name: 'Hamburger buns', aliases: ['burger buns', 'brioche buns', 'soft rolls', 'sandwich rolls'], aisle: 'Bakery' },
  { name: 'Hot dog buns', aliases: ['hot dog rolls', 'frankfurter rolls'], aisle: 'Bakery' },

  // ── Frozen ────────────────────────────────────────────────────────────────
  { name: 'Frozen peas', aliases: ['frozen green peas', 'sweet peas', 'green peas'], aisle: 'Frozen' },
  { name: 'Frozen corn', aliases: ['frozen corn kernels', 'frozen sweet corn'], aisle: 'Frozen' },
  { name: 'Frozen spinach', aliases: ['frozen chopped spinach', 'thawed frozen spinach'], aisle: 'Frozen' },
  { name: 'Frozen edamame', aliases: ['edamame', 'shelled edamame', 'frozen shelled edamame'], aisle: 'Frozen' },
  { name: 'Frozen mixed vegetables', aliases: ['mixed vegetables', 'stir-fry vegetables', 'frozen stir-fry mix'], aisle: 'Frozen' },
  { name: 'Frozen broccoli', aliases: ['frozen broccoli florets'], aisle: 'Frozen' },
  { name: 'Frozen berries', aliases: ['mixed frozen berries', 'frozen mixed berries', 'frozen blueberries', 'frozen strawberries'], aisle: 'Frozen' },

  // ── Beverages ─────────────────────────────────────────────────────────────
  { name: 'Orange juice', aliases: ['OJ', 'fresh orange juice', 'fresh-squeezed orange juice'], aisle: 'Beverages' },
  { name: 'Apple juice', aliases: ['apple cider', 'fresh apple juice', 'apple juice/cider'], aisle: 'Beverages' },
  { name: 'Coconut water', aliases: ['fresh coconut water', 'unsweetened coconut water'], aisle: 'Beverages' },
]
